gem "rails", "3.0.0.beta"
gem "mongo"
gem "mongo_ext"
gem "ruby-openid"
gem "rack-openid"
gem "mongoid", :git => "git://github.com/durran/mongoid.git", :branch => "prerelease"
gem "haml"
gem "RedCloth"
gem "carrierwave", :git => "git://github.com/jnicklas/carrierwave.git"
