development:
  sessions:
    default:
      database: blabbr_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: blabbr_test
      hosts:
        - localhost:27017
